os: linux
language: android
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-android-support
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b alpha --depth 1
script:
  - ./flutter/bin/flutter -v build apk

cache:
  directories:
    - $HOME/.pub-cache
