sudo: required
language: android
os:
  - linux
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25 - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21
before_install:
  - git clone -b alpha https://github.com/flutter/flutter.git
install:
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - export PATH=./flutter/bin:$PATH
script:
  - flutter build apk
